[package]
name = "tic-solved"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
dotenv = "0.15.0"
env_logger = "0.10.1"
itertools = "0.12.0"
log = "0.4.20"
rstest = "0.18.2"
